package report

import (
	"time"
)

type (
	// Report is a report generated by the github checker rules engine
	Report struct {
		Generated time.Time `json:"generated"`
		Summary   Summary   `json:"summary"`
	}

	// Summary is a headline summary of numbers such as total users in the
	// organisation, and those that have passed/failed rules checks
	Summary struct {
		TotalUsers             int `json:"total_users"`
		UsersMissingMFA        int `json:"missing_mfa"`
		AdminUsers             int `json:"admin_users"`
		AdminUsersFailingRules int `json:"admin_users_failing"`
	}
)
